import {
  File,
  FileText,
  FileCode2,
  FileJson,
  FileVideo,
  FileAudio,
  FileSpreadsheet,
  FileArchive,
  FolderOpen,
  Terminal,
  Settings,
  Image,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

interface FileIconProps {
  isDir: boolean;
  extension: string;
  className?: string;
}

const iconMap: Record<string, { icon: LucideIcon; color: string }> = {
  dir: { icon: FolderOpen, color: "#3b82f6" },
  png: { icon: Image, color: "#22c55e" },
  jpg: { icon: Image, color: "#22c55e" },
  jpeg: { icon: Image, color: "#22c55e" },
  gif: { icon: Image, color: "#22c55e" },
  bmp: { icon: Image, color: "#22c55e" },
  svg: { icon: Image, color: "#22c55e" },
  webp: { icon: Image, color: "#22c55e" },
  ico: { icon: Image, color: "#22c55e" },
  mp4: { icon: FileVideo, color: "#a855f7" },
  avi: { icon: FileVideo, color: "#a855f7" },
  mkv: { icon: FileVideo, color: "#a855f7" },
  mov: { icon: FileVideo, color: "#a855f7" },
  wmv: { icon: FileVideo, color: "#a855f7" },
  flv: { icon: FileVideo, color: "#a855f7" },
  webm: { icon: FileVideo, color: "#a855f7" },
  mp3: { icon: FileAudio, color: "#f97316" },
  wav: { icon: FileAudio, color: "#f97316" },
  flac: { icon: FileAudio, color: "#f97316" },
  aac: { icon: FileAudio, color: "#f97316" },
  ogg: { icon: FileAudio, color: "#f97316" },
  wma: { icon: FileAudio, color: "#f97316" },
  txt: { icon: FileText, color: "#64748b" },
  md: { icon: FileText, color: "#64748b" },
  log: { icon: FileText, color: "#64748b" },
  pdf: { icon: FileText, color: "#ef4444" },
  doc: { icon: FileText, color: "#2563eb" },
  docx: { icon: FileText, color: "#2563eb" },
  rtf: { icon: FileText, color: "#64748b" },
  js: { icon: FileCode2, color: "#eab308" },
  ts: { icon: FileCode2, color: "#3b82f6" },
  jsx: { icon: FileCode2, color: "#06b6d4" },
  tsx: { icon: FileCode2, color: "#06b6d4" },
  py: { icon: FileCode2, color: "#16a34a" },
  rs: { icon: FileCode2, color: "#ea580c" },
  java: { icon: FileCode2, color: "#dc2626" },
  c: { icon: FileCode2, color: "#2563eb" },
  cpp: { icon: FileCode2, color: "#2563eb" },
  h: { icon: FileCode2, color: "#60a5fa" },
  go: { icon: FileCode2, color: "#0891b2" },
  html: { icon: FileCode2, color: "#f97316" },
  css: { icon: FileCode2, color: "#60a5fa" },
  scss: { icon: FileCode2, color: "#ec4899" },
  less: { icon: FileCode2, color: "#93c5fd" },
  vue: { icon: FileCode2, color: "#22c55e" },
  svelte: { icon: FileCode2, color: "#f97316" },
  rb: { icon: FileCode2, color: "#ef4444" },
  php: { icon: FileCode2, color: "#6366f1" },
  swift: { icon: FileCode2, color: "#f97316" },
  kt: { icon: FileCode2, color: "#a855f7" },
  lua: { icon: FileCode2, color: "#3b82f6" },
  sh: { icon: FileCode2, color: "#22c55e" },
  bash: { icon: FileCode2, color: "#22c55e" },
  ps1: { icon: FileCode2, color: "#3b82f6" },
  json: { icon: FileJson, color: "#ca8a04" },
  xml: { icon: FileJson, color: "#fb923c" },
  yaml: { icon: FileJson, color: "#f87171" },
  yml: { icon: FileJson, color: "#f87171" },
  csv: { icon: FileSpreadsheet, color: "#16a34a" },
  sql: { icon: FileJson, color: "#3b82f6" },
  xlsx: { icon: FileSpreadsheet, color: "#16a34a" },
  xls: { icon: FileSpreadsheet, color: "#16a34a" },
  zip: { icon: FileArchive, color: "#eab308" },
  rar: { icon: FileArchive, color: "#eab308" },
  "7z": { icon: FileArchive, color: "#eab308" },
  tar: { icon: FileArchive, color: "#eab308" },
  gz: { icon: FileArchive, color: "#eab308" },
  bz2: { icon: FileArchive, color: "#eab308" },
  xz: { icon: FileArchive, color: "#eab308" },
  exe: { icon: Terminal, color: "#475569" },
  msi: { icon: Terminal, color: "#475569" },
  bat: { icon: Terminal, color: "#475569" },
  cmd: { icon: Terminal, color: "#475569" },
  com: { icon: Terminal, color: "#475569" },
  toml: { icon: Settings, color: "#6b7280" },
  ini: { icon: Settings, color: "#6b7280" },
  cfg: { icon: Settings, color: "#6b7280" },
  conf: { icon: Settings, color: "#6b7280" },
  env: { icon: Settings, color: "#6b7280" },
  lock: { icon: Settings, color: "#9ca3af" },
};

export default function FileIcon({ isDir, extension, className }: FileIconProps) {
  const key = isDir ? "dir" : extension.toLowerCase();
  const entry = iconMap[key] ?? { icon: File, color: "#9ca3af" };
  const Icon = entry.icon;

  return <Icon size={16} style={{ flexShrink: 0, color: entry.color }} className={className} />;
}
